<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Papuma.Kernel" />
    <InternalsVisibleTo Include="Papuma.Kernel.Tests" />
    <InternalsVisibleTo Include="Papuma.Kernel.Local" />
    <InternalsVisibleTo Include="Papuma.Kernel.Local.Tests" />
  </ItemGroup>

</Project>
